spring.application.name=ulaResort

server.port=8080

#ORACLE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=mayoralUlaResort
spring.datasource.password=mayoralUlaResort
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#oracle dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.sql.init.mode=always

#logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


