


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HABITACIONES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- BEGIN
--     -- Elimina la tabla de bitácora
--     EXECUTE IMMEDIATE 'DROP TABLE HABITACIONES_BIT CASCADE CONSTRAINTS ';
-- EXCEPTION
--     WHEN OTHERS THEN NULL; -- Ignora errores
-- END;
-- /
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HABITACIONES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- BEGIN
--    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HABITACIONES_BIT';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

-- Secuencia para generar IDs consecutivos
CREATE SEQUENCE SEQ_HABITACIONES START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE SEQ_HABITACIONES_BIT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;




CREATE TABLE HABITACIONES (
    ID_HABITACION NUMBER PRIMARY KEY,
    NUMERO_HABITACION VARCHAR2(10) NOT NULL,
    PISO NUMBER ,
    DESCRIPCION VARCHAR2(200),
    PRECIO_BASE_NOCHE NUMBER(10,2) NOT NULL,
    CAPACIDAD NUMBER NOT NULL,
    ID_CATALOGO_HABITACION NUMBER NOT NULL,
    DISPONIBLE VARCHAR2(200),
    ESTADO NUMBER(1) DEFAULT 1,

    CONSTRAINT FK_HABITACION_CATALOGO
    FOREIGN KEY (ID_CATALOGO_HABITACION)
    REFERENCES CATALOGO_HABITACION(ID_CATALOGO_HABITACION)
);

-- Documentación de la tabla HABITACIONES
COMMENT ON TABLE HABITACIONES IS 'Tabla que almacena las habitaciones disponibles del hotel';

COMMENT ON COLUMN HABITACIONES.ID_HABITACION IS 'Identificador único de la habitación';
COMMENT ON COLUMN HABITACIONES.NUMERO_HABITACION IS 'Número o código asignado a la habitación';
COMMENT ON COLUMN HABITACIONES.PISO IS 'Piso donde se encuentra ubicada la habitación';
COMMENT ON COLUMN HABITACIONES.DESCRIPCION IS 'Descripción general de la habitación';
COMMENT ON COLUMN HABITACIONES.PRECIO_BASE_NOCHE IS 'Precio base por noche de la habitación';
COMMENT ON COLUMN HABITACIONES.CAPACIDAD IS 'Capacidad máxima de personas en la habitación';
COMMENT ON COLUMN HABITACIONES.ID_CATALOGO_HABITACION IS 'Referencia al tipo de habitación (catálogo)';
COMMENT ON COLUMN HABITACIONES.DISPONIBLE IS 'Estado de disponibilidad de la habitación';
COMMENT ON COLUMN HABITACIONES.ESTADO IS 'Estado lógico del registro (1 activo, 0 inactivo)';