

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RESERVACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- BEGIN
--     -- Elimina la tabla de bitácora
--     EXECUTE IMMEDIATE 'DROP TABLE RESERVACION_BIT CASCADE CONSTRAINTS ';
-- EXCEPTION
--     WHEN OTHERS THEN NULL; -- Ignora errores
-- END;
-- /
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESERVACION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- BEGIN
--    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESERVACION_BIT';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

-- Secuencia para generar IDs consecutivos
CREATE SEQUENCE SEQ_RESERVACION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE SEQ_RESERVACION_BIT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;


CREATE TABLE RESERVACION (
    ID_RESERVACION NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    ID_HABITACION NUMBER NOT NULL,
    ID_TARJETA NUMBER,
    ID_PAQUETE NUMBER,
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    CANTIDAD_HUESPEDES NUMBER NOT NULL,
    TOTAL_PAGAR NUMBER(10,2) NOT NULL,
    ESTATUS_RESERVACION VARCHAR2(50) NOT NULL,
    FECHA_RESERVACION DATE DEFAULT SYSDATE,
    ESTADO NUMBER(1) DEFAULT 1,

    CONSTRAINT FK_RESERVACION_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE),

    CONSTRAINT FK_RESERVACION_HABITACION
        FOREIGN KEY (ID_HABITACION)
        REFERENCES CATALOGO_HABITACION(ID_CATALOGO_HABITACION),

    CONSTRAINT FK_RESERVACION_TARJETA
        FOREIGN KEY (ID_TARJETA)
        REFERENCES TARJETAS_CREDITO(ID_TARJETA),

    CONSTRAINT FK_RESERVACION_PAQUETE
        FOREIGN KEY (ID_PAQUETE)
        REFERENCES PAQUETE_PROMOCIONAL(ID_PAQUETE)
);

-- Documentación de la tabla RESERVACION
COMMENT ON TABLE RESERVACION IS 'Tabla que almacena las reservaciones realizadas por los clientes';

COMMENT ON COLUMN RESERVACION.ID_RESERVACION IS 'Identificador único de la reservación';
COMMENT ON COLUMN RESERVACION.ID_CLIENTE IS 'Referencia al cliente que realiza la reservación';
COMMENT ON COLUMN RESERVACION.ID_HABITACION IS 'Referencia a la habitación reservada';
COMMENT ON COLUMN RESERVACION.ID_TARJETA IS 'Referencia a la tarjeta de crédito utilizada para el pago';
COMMENT ON COLUMN RESERVACION.ID_PAQUETE IS 'Referencia al paquete promocional aplicado (opcional)';
COMMENT ON COLUMN RESERVACION.FECHA_ENTRADA IS 'Fecha de inicio de la estancia';
COMMENT ON COLUMN RESERVACION.FECHA_SALIDA IS 'Fecha de salida de la estancia';
COMMENT ON COLUMN RESERVACION.CANTIDAD_HUESPEDES IS 'Número de huéspedes en la reservación';
COMMENT ON COLUMN RESERVACION.TOTAL_PAGAR IS 'Monto total a pagar por la reservación';
COMMENT ON COLUMN RESERVACION.ESTATUS_RESERVACION IS 'Estado de la reservación (PENDIENTE, CONFIRMADA, CANCELADA, FINALIZADA)';
COMMENT ON COLUMN RESERVACION.FECHA_RESERVACION IS 'Fecha en que se realizó la reservación';
COMMENT ON COLUMN RESERVACION.ESTADO IS 'Estado lógico del registro (1 activo, 0 inactivo)';