

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TARJETAS_CREDITO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- BEGIN
--     -- Elimina la tabla de bitácora
--     EXECUTE IMMEDIATE 'DROP TABLE TARJETAS_CREDITO_BIT CASCADE CONSTRAINTS ';
-- EXCEPTION
--     WHEN OTHERS THEN NULL; -- Ignora errores
-- END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TARJETAS_CREDITO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- BEGIN
--     EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TARJETAS_CREDITO_BIT';
-- EXCEPTION
--     WHEN OTHERS THEN NULL;
-- END;
-- /

-- Secuencia para generar IDs consecutivos
CREATE SEQUENCE SEQ_TARJETAS_CREDITO START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE SEQ_TARJETAS_CREDITO_BIT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;


CREATE TABLE TARJETAS_CREDITO (
    ID_TARJETA NUMBER PRIMARY KEY,
    TITULAR VARCHAR2(100) NOT NULL,
    NUMERO_TARJETA VARCHAR2(20) NOT NULL,
    FECHA_EXPIRACION DATE NOT NULL,
    CVV VARCHAR2(4) NOT NULL,
    BANCO VARCHAR2(50),
    TIPO_TARJETA VARCHAR2(20),
    ID_CLIENTE NUMBER,
    ESTADO NUMBER(1) DEFAULT 1,

    CONSTRAINT FK_TARJETA_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
);


-- Documentación de la tabla TARJETAS_CREDITO
COMMENT ON TABLE TARJETAS_CREDITO IS 'Tabla que almacena las tarjetas de crédito registradas de los clientes';

COMMENT ON COLUMN TARJETAS_CREDITO.ID_TARJETA IS 'Identificador único de la tarjeta de crédito';
COMMENT ON COLUMN TARJETAS_CREDITO.TITULAR IS 'Nombre del titular de la tarjeta';
COMMENT ON COLUMN TARJETAS_CREDITO.NUMERO_TARJETA IS 'Número de la tarjeta de crédito';
COMMENT ON COLUMN TARJETAS_CREDITO.FECHA_EXPIRACION IS 'Fecha de expiración de la tarjeta';
COMMENT ON COLUMN TARJETAS_CREDITO.CVV IS 'Código de seguridad de la tarjeta (CVV)';
COMMENT ON COLUMN TARJETAS_CREDITO.BANCO IS 'Banco emisor de la tarjeta';
COMMENT ON COLUMN TARJETAS_CREDITO.TIPO_TARJETA IS 'Tipo de tarjeta (Crédito, Débito, etc.)';
COMMENT ON COLUMN TARJETAS_CREDITO.ID_CLIENTE IS 'Referencia al cliente propietario de la tarjeta';
COMMENT ON COLUMN TARJETAS_CREDITO.ESTADO IS 'Estado lógico del registro (1 activo, 0 inactivo)';