

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CATALOGO_HABITACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- BEGIN
--     -- Elimina la tabla de bitácora
--     EXECUTE IMMEDIATE 'DROP TABLE CATALOGO_HABITACION_BIT CASCADE CONSTRAINTS ';
-- EXCEPTION
--     WHEN OTHERS THEN NULL; -- Ignora errores
-- END;
-- /
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CATALOGO_HABITACION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- BEGIN
--    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CATALOGO_HABITACION_BIT';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

-- Secuencia para generar IDs consecutivos
CREATE SEQUENCE SEQ_CATALOGO_HABITACION START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE SEQ_CATALOGO_HABITACION_BIT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;



CREATE TABLE CATALOGO_HABITACION (
    ID_CATALOGO_HABITACION NUMBER PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR2(100) NOT NULL,
    CAPACIDAD_PERSONAS NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(200),
    PRECIO_BASE NUMBER(10,2) NOT NULL,
    AMENIDADES VARCHAR2(500),
    ESTADO NUMBER DEFAULT 1
);

-- Documentación de la tabla CATALOGO_HABITACION
COMMENT ON TABLE CATALOGO_HABITACION IS 'Catálogo de tipos de habitación disponibles en el hotel';

COMMENT ON COLUMN CATALOGO_HABITACION.ID_CATALOGO_HABITACION IS 'Identificador único del catálogo de habitación';
COMMENT ON COLUMN CATALOGO_HABITACION.NOMBRE_CATEGORIA IS 'Nombre de la categoría de habitación';
COMMENT ON COLUMN CATALOGO_HABITACION.CAPACIDAD_PERSONAS IS 'Capacidad máxima de personas por habitación';
COMMENT ON COLUMN CATALOGO_HABITACION.DESCRIPCION IS 'Descripción general de la habitación';
COMMENT ON COLUMN CATALOGO_HABITACION.PRECIO_BASE IS 'Precio base por noche de la habitación';
COMMENT ON COLUMN CATALOGO_HABITACION.AMENIDADES IS 'Servicios o amenidades incluidas en la habitación';
COMMENT ON COLUMN CATALOGO_HABITACION.ESTADO IS 'Estado lógico del registro (1 activo, 0 inactivo)';