

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- BEGIN
--    EXECUTE IMMEDIATE 'DROP TABLE CLIENTE_BIT CASCADE CONSTRAINTS';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- BEGIN
--    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE_BIT';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

-- Secuencia para generar IDs consecutivos
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE SEQ_CLIENTE_BIT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;



CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100) UNIQUE,
    DIRECCION VARCHAR2(200),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    ESTADO NUMBER DEFAULT 1
);

-- Documentación de la tabla CLIENTE
COMMENT ON TABLE CLIENTE IS 'Tabla que almacena la información de los clientes del sistema';

COMMENT ON COLUMN CLIENTE.ID_CLIENTE IS 'Identificador único del cliente';
COMMENT ON COLUMN CLIENTE.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTE.APELLIDO IS 'Apellido del cliente';
COMMENT ON COLUMN CLIENTE.TELEFONO IS 'Número telefónico de contacto del cliente';
COMMENT ON COLUMN CLIENTE.CORREO IS 'Correo electrónico del cliente (único)';
COMMENT ON COLUMN CLIENTE.DIRECCION IS 'Dirección del cliente';
COMMENT ON COLUMN CLIENTE.FECHA_REGISTRO IS 'Fecha de registro del cliente en el sistema';
COMMENT ON COLUMN CLIENTE.ESTADO IS 'Estado lógico del registro (1 activo, 0 inactivo)';