





-- Ejemplos de inserción en CLIENTE

INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDO, TELEFONO, CORREO, DIRECCION, FECHA_REGISTRO, ESTADO)
VALUES (1, 'Juan', 'Pérez', '9511234567', 'juan.perez@gmail.com', 'Centro, Huajuapan', SYSDATE, 1);

INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDO, TELEFONO, CORREO, DIRECCION, FECHA_REGISTRO, ESTADO)
VALUES (4, 'Ana', 'Hernández', '9514447788', 'ana.hernandez@gmail.com', 'Col. Centro, CDMX', SYSDATE, 1);

INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, APELLIDO, TELEFONO, CORREO, DIRECCION, FECHA_REGISTRO, ESTADO)
VALUES (5, 'Luis', 'Martínez', '9513332211', 'luis.martinez@gmail.com', 'Oaxaca Centro', SYSDATE, 1);
Commit ;

-- Ejemplos de inserción en HABITACIONES

INSERT INTO HABITACIONES
(ID_HABITACION, NUMERO_HABITACION, PISO, DESCRIPCION, PRECIO_BASE_NOCHE, CAPACIDAD, ID_CATALOGO_HABITACION, DISPONIBLE, ESTADO)
VALUES
(1, '101', 1, 'Habitación sencilla con cama individual', 500.00, 1, 1, 'SI', 1);

INSERT INTO HABITACIONES
(ID_HABITACION, NUMERO_HABITACION, PISO, DESCRIPCION, PRECIO_BASE_NOCHE, CAPACIDAD, ID_CATALOGO_HABITACION, DISPONIBLE, ESTADO)
VALUES
(4, '202', 2, 'Habitación familiar amplia', 1200.00, 4, 2, 'SI', 1);

INSERT INTO HABITACIONES
(ID_HABITACION, NUMERO_HABITACION, PISO, DESCRIPCION, PRECIO_BASE_NOCHE, CAPACIDAD, ID_CATALOGO_HABITACION, DISPONIBLE, ESTADO)
VALUES
(5, '301', 3, 'Suite presidencial con balcón', 2500.00, 2, 3, 'SI', 1);
Commit ;


-- Ejemplos de inserción en CATALOGO_HABITACION


INSERT INTO CATALOGO_HABITACION
(ID_CATALOGO_HABITACION, NOMBRE_CATEGORIA, CAPACIDAD_PERSONAS, DESCRIPCION, PRECIO_BASE, AMENIDADES, ESTADO)
VALUES
(4, 'Familiar', 4, 'Habitación amplia para familia', 1200.00, 'WiFi, TV, aire acondicionado, cocina pequeña', 1);

INSERT INTO CATALOGO_HABITACION
(ID_CATALOGO_HABITACION, NOMBRE_CATEGORIA, CAPACIDAD_PERSONAS, DESCRIPCION, PRECIO_BASE, AMENIDADES, ESTADO)
VALUES
(5, 'Presidencial', 2, 'Suite de lujo premium', 2500.00, 'Vista panorámica, jacuzzi, sala privada, servicio VIP', 1);
Commit ;



-- Ejemplos de inserción en TARJETAS_CREDITO


INSERT INTO TARJETAS_CREDITO
(ID_TARJETA, TITULAR, NUMERO_TARJETA, FECHA_EXPIRACION, CVV, BANCO, TIPO_TARJETA, ID_CLIENTE, ESTADO)
VALUES
(3, 'Carlos García', '378282246310005', TO_DATE('2028-03-01','YYYY-MM-DD'), '789', 'Banamex', 'CRÉDITO', 3, 1);

INSERT INTO TARJETAS_CREDITO
(ID_TARJETA, TITULAR, NUMERO_TARJETA, FECHA_EXPIRACION, CVV, BANCO, TIPO_TARJETA, ID_CLIENTE, ESTADO)
VALUES
(4, 'Ana Hernández', '6011000990139424', TO_DATE('2027-05-01','YYYY-MM-DD'), '321', 'HSBC', 'DÉBITO', 4, 1);

INSERT INTO TARJETAS_CREDITO
(ID_TARJETA, TITULAR, NUMERO_TARJETA, FECHA_EXPIRACION, CVV, BANCO, TIPO_TARJETA, ID_CLIENTE, ESTADO)
VALUES
(5, 'Luis Martínez', '3530111333300000', TO_DATE('2029-10-01','YYYY-MM-DD'), '654', 'Scotiabank', 'CRÉDITO', 5, 1);
Commit ;


-- Ejemplos de inserción en PAQUETE_PROMOCIONAL


INSERT INTO PAQUETE_PROMOCIONAL
(ID_PAQUETE, NOMBRE_PAQUETE, DESCRIPCION, PORCENTAJE_DESCUENTO, FECHA_INICIO_VIGENCIA, FECHA_FIN_VIGENCIA, CONDICIONES, ESTADO)
VALUES
(2, 'Vacaciones Familiares', 'Descuento para familias', 10.00, TO_DATE('2026-06-01','YYYY-MM-DD'), TO_DATE('2026-12-31','YYYY-MM-DD'), 'Mínimo 3 huéspedes', 1);

INSERT INTO PAQUETE_PROMOCIONAL
(ID_PAQUETE, NOMBRE_PAQUETE, DESCRIPCION, PORCENTAJE_DESCUENTO, FECHA_INICIO_VIGENCIA, FECHA_FIN_VIGENCIA, CONDICIONES, ESTADO)
VALUES
(3, 'Fin de Semana', 'Promoción de fin de semana', 20.00, TO_DATE('2026-07-01','YYYY-MM-DD'), TO_DATE('2026-09-30','YYYY-MM-DD'), 'Solo viernes a domingo', 1);
Commit ;


-- Reservación 1
INSERT INTO RESERVACION (
    ID_RESERVACION, ID_CLIENTE, ID_HABITACION, ID_TARJETA, ID_PAQUETE,
    FECHA_ENTRADA, FECHA_SALIDA, CANTIDAD_HUESPEDES, TOTAL_PAGAR,
    ESTATUS_RESERVACION, FECHA_RESERVACION, ESTADO
) VALUES (
    1, 5, 3, 5, 3,
    TO_DATE('2026-07-01','YYYY-MM-DD'), TO_DATE('2026-07-05','YYYY-MM-DD'),
    2, 2000.00,
    'CONFIRMADA', SYSDATE, 1
);

-- Reservación 2
INSERT INTO RESERVACION (
    ID_RESERVACION, ID_CLIENTE, ID_HABITACION, ID_TARJETA, ID_PAQUETE,
    FECHA_ENTRADA, FECHA_SALIDA, CANTIDAD_HUESPEDES, TOTAL_PAGAR,
    ESTATUS_RESERVACION, FECHA_RESERVACION, ESTADO
) VALUES (
    2, 5, 4, 5, 2,
    TO_DATE('2026-07-10','YYYY-MM-DD'), TO_DATE('2026-07-12','YYYY-MM-DD'),
    3, 1500.00,
    'CONFIRMADA', SYSDATE, 1
);

COMMIT;


 SELECT * FROM CLIENTE;
 SELECT * FROM CATALOGO_HABITACION;
 SELECT * FROM HABITACIONES;
 SELECT * FROM PAQUETE_PROMOCIONAL;
 SELECT * FROM RESERVACION;
 SELECT * FROM TARJETAS_CREDITO;


SELECT SEQ_CLIENTE.NEXTVAL FROM dual;
SELECT SEQ_RESERVACION.NEXTVAL FROM dual;


