


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAQUETE_PROMOCIONAL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- BEGIN
--     -- Elimina la tabla de bitácora
--     EXECUTE IMMEDIATE 'DROP TABLE PAQUETE_PROMOCIONAL_BIT CASCADE CONSTRAINTS ';
-- EXCEPTION
--     WHEN OTHERS THEN NULL; -- Ignora errores
-- END;
-- /
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAQUETE_PROMOCIONAL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- BEGIN
--    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAQUETE_PROMOCIONAL_BIT';
-- EXCEPTION WHEN OTHERS THEN NULL;
-- END;
-- /

-- Secuencia para generar IDs consecutivos
CREATE SEQUENCE SEQ_PAQUETE_PROMOCIONAL START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;
-- CREATE SEQUENCE SEQ_PAQUETE_PROMOCIONAL_BIT START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;



CREATE TABLE PAQUETE_PROMOCIONAL (
    ID_PAQUETE NUMBER PRIMARY KEY,
    NOMBRE_PAQUETE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    PORCENTAJE_DESCUENTO NUMBER(5,2) ,
    FECHA_INICIO_VIGENCIA DATE ,
    FECHA_FIN_VIGENCIA DATE NOT NULL,
    CONDICIONES VARCHAR2(500),
    ESTADO NUMBER(1) DEFAULT 1
);

-- Documentación de la tabla PAQUETE_PROMOCIONAL
COMMENT ON TABLE PAQUETE_PROMOCIONAL IS 'Tabla que almacena los paquetes promocionales del hotel';

COMMENT ON COLUMN PAQUETE_PROMOCIONAL.ID_PAQUETE IS 'Identificador único del paquete promocional';
COMMENT ON COLUMN PAQUETE_PROMOCIONAL.NOMBRE_PAQUETE IS 'Nombre del paquete promocional';
COMMENT ON COLUMN PAQUETE_PROMOCIONAL.DESCRIPCION IS 'Descripción general del paquete';
COMMENT ON COLUMN PAQUETE_PROMOCIONAL.PORCENTAJE_DESCUENTO IS 'Porcentaje de descuento aplicado al paquete';
COMMENT ON COLUMN PAQUETE_PROMOCIONAL.FECHA_INICIO_VIGENCIA IS 'Fecha de inicio de vigencia del paquete';
COMMENT ON COLUMN PAQUETE_PROMOCIONAL.FECHA_FIN_VIGENCIA IS 'Fecha de fin de vigencia del paquete';
COMMENT ON COLUMN PAQUETE_PROMOCIONAL.CONDICIONES IS 'Condiciones o restricciones del paquete';
COMMENT ON COLUMN PAQUETE_PROMOCIONAL.ESTADO IS 'Estado lógico del registro (1 activo, 0 inactivo)';